/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CallButton: typeof import('./src/components/SideBar/call-button.vue')['default']
    CheckSystemButton: typeof import('./src/components/button/checkSystemButton.vue')['default']
    CommonMenu: typeof import('./src/components/commonMenu/index.vue')['default']
    ContactButton: typeof import('./src/components/SideBar/contact-button.vue')['default']
    EcCanvas: typeof import('./src/components/myEcharts/ec-canvas/ec-canvas.vue')['default']
    FreeOverlay: typeof import('./src/components/homeModal/freeOverlay/index.vue')['default']
    FullPreview: typeof import('./src/components/fullPreview/index.vue')['default']
    GuideOverlay: typeof import('./src/components/homeModal/guideOverlay/index.vue')['default']
    'Icon.h5': typeof import('./src/components/alIconfont/icon.h5.vue')['default']
    'Icon.weapp': typeof import('./src/components/alIconfont/icon.weapp.vue')['default']
    Lock: typeof import('./src/components/lock/index.vue')['default']
    MyCircleProgress: typeof import('./src/components/MyCircleProgress/index.vue')['default']
    MyEcharts: typeof import('./src/components/myEcharts/index.vue')['default']
    MyToast: typeof import('./src/components/myToast/index.vue')['default']
    NutAnimate: typeof import('@nutui/nutui-taro')['Animate']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutNoticebar: typeof import('@nutui/nutui-taro')['Noticebar']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
    NutWatermark: typeof import('@nutui/nutui-taro')['Watermark']
    OpenOutLinkTipPop: typeof import('./src/components/pop/openOutLinkTipPop/index.vue')['default']
    PostButton: typeof import('./src/components/SideBar/post-button.vue')['default']
    PostPreList: typeof import('./src/components/postPreList/index.vue')['default']
    RenewOverlay: typeof import('./src/components/homeModal/renewOverlay/index.vue')['default']
    ShareButton: typeof import('./src/components/SideBar/share-button.vue')['default']
    SideBar: typeof import('./src/components/SideBar/index.vue')['default']
    SvgaPlay: typeof import('./src/components/svgaPlay/index.vue')['default']
    UpdatePop: typeof import('./src/components/pop/updatePop/index.vue')['default']
    WggwStepsLine: typeof import('./src/components/wggwStepsLine/index.vue')['default']
  }
}
